services:

  eldoria-backup:
    build: 
      context: ../eldoria-backup
      dockerfile: dockerfile
    image: eldoria-backup:latest
    container_name: eldoria-backup
    restart: unless-stopped
    volumes:
      - eldoria-server:/minecraft
      - eldoria-backups:/backups
    networks:
      - eldoria-net
    depends_on:
      - eldoria-server
    environment:
      - PYTHONPATH=/app
      - TZ=${TZ}
      - KEEP_BACKUPS=${KEEP_BACKUPS}
      - BACKUP_INTERVAL=${BACKUP_INTERVAL}

  eldoria-backend:
    build:
      context: ../eldoria-backend
      dockerfile: dockerfile
    image: eldoria-backend:latest
    container_name: eldoria-backend
    restart: unless-stopped
    volumes:
      - eldoria-server:/minecraft
      - backend-config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - "8000"
    networks:
      - eldoria-net
    depends_on:
      - eldoria-server
    environment:
      - TZ=${TZ}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - MINECRAFT_RCON_PASSWORD=${MINECRAFT_RCON_PASSWORD}
      - MODRINTH_AUTHORIZATION=${MODRINTH_AUTHORIZATION}

  eldoria-frontend:
    build:
      context: ../eldoria-frontend
      dockerfile: dockerfile
    image: eldoria-frontend:latest
    container_name: eldoria-frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy-data:/data
      - caddy-config:/config
    networks:
      - eldoria-net
    depends_on:
      - eldoria-backend
    environment:
      - TZ=${TZ}

  eldoria-server:
    build: 
      context: .
      dockerfile: dockerfile
      args:
        MC_VERSION: ${MC_VERSION}
        FABRIC_LOADER_VERSION: ${FABRIC_LOADER_VERSION}
        INSTALLER_VERSION: ${INSTALLER_VERSION}
    image: eldoria-server:latest
    container_name: eldoria-server
    restart: unless-stopped
    ports:
      - "25565:25565"
      - "24454:24454/udp" 
      - "24454:24454/tcp"
    volumes:
      - eldoria-server:/minecraft
    environment:
      - MEMORY=${MEMORY}
      - TZ=${TZ}
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 25565 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - eldoria-net

networks:
  eldoria-net:
    driver: bridge

volumes:
  eldoria-server:
    driver: local
  backend-config:
    driver: local
  eldoria-backups:
    driver: local
  caddy-data:
    driver: local
  caddy-config:
    driver: local