services:
  monitor:
    build: 
      context: ./monitor-system
    image: minecraft-monitor-system:latest
    container_name: minecraft-monitor-system
    restart: unless-stopped
    volumes:
      - ./server-files/mods-list.json:/app/mods-list.json:ro
      
      - minecraft-logs:/minecraft/logs:ro
      - minecraft-world:/minecraft/server-world:ro
      - minecraft-mods:/minecraft/mods
      
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - monitor-cache:/app/cache
    depends_on:
      - minecraft
    networks:
      - minecraft-net
    environment:
      - PYTHONPATH=/app
      - TZ=America/Sao_Paulo
      - CHECK_INTERVAL=60

  backup-system:
    build: 
      context: ./backup-system
    image: minecraft-backup-system:latest
    container_name: minecraft-backup-system
    restart: unless-stopped
    volumes:
      - ./backups:/app/backups

      - minecraft-world:/minecraft/server-world:ro
    networks:
      - minecraft-net
    depends_on:
      - minecraft
    environment:
      - PYTHONPATH=/app
      - TZ=America/Sao_Paulo
      - KEEP_BACKUPS=5
      - BACKUP_INTERVAL=3600

  minecraft:
    build: 
      context: .
      args:
        MC_VERSION: "1.21.1"
        FABRIC_LOADER_VERSION: "0.18.0"
        INSTALLER_VERSION: "1.1.0"
    image: minecraft-server:latest
    container_name: minecraft-server
    restart: unless-stopped
    ports:
      - "25565:25565"
      - "25575:25575"
      - "24454:24454/udp" 
      - "24454:24454/tcp"
    volumes:
      - ./config:/minecraft/config
      - ./config/ops.json:/minecraft/ops.json:ro
      - ./config/server.properties:/minecraft/server.properties:ro
      - ./config/whitelist.json:/minecraft/whitelist.json:ro
      - ./config/banned-ips.json:/minecraft/banned-ips.json:ro
      - ./config/banned-players.json:/minecraft/banned-players.json:ro

      - minecraft-world:/minecraft/server-world
      - minecraft-mods:/minecraft/mods
      - minecraft-logs:/minecraft/logs
    environment:
      - MEMORY=-Xmx6G -Xms3G
      - TZ=America/Sao_Paulo
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 25565 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - minecraft-net

networks:
  minecraft-net:
    driver: bridge

volumes:
  minecraft-world:
    driver: local
  minecraft-logs:
    driver: local
  minecraft-mods:
    driver: local
  monitor-cache:
    driver: local