services:
  minecraft:
    build: 
      context: .
      args:
        MC_VERSION: "1.21.1"
        FABRIC_LOADER_VERSION: "0.18.0"
        INSTALLER_VERSION: "1.1.0"
    image: minecraft-server:latest
    container_name: minecraft-server
    restart: unless-stopped
    ports:
      - "25565:25565"
      - "24454:24454/udp" 
      - "24454:24454/tcp"
    volumes:
      - ./minecraft-data/backups:/minecraft/backups
      - ./server-config/server.properties:/minecraft/server.properties:ro
      - ./server-config/voicechat-server.properties:/minecraft/config/voicechat/voicechat-server.properties:ro

      - minecraft-world:/minecraft/server-world
      - minecraft-mods:/minecraft/mods
      - minecraft-logs:/minecraft/logs
    environment:
      - MEMORY=-Xmx6G -Xms3G
      - TZ=America/Sao_Paulo
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 25565 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - minecraft-net

networks:
  minecraft-net:
    driver: bridge

volumes:
  minecraft-world:
    driver: local
  minecraft-logs:
    driver: local
  minecraft-mods:
    driver: local